# Generated by Django 4.0.6 on 2022-07-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
